appName: dual-region-app
imageTag: v0.0.1
environment: dev
configVersion: 0
deployment:
  replicas: 2
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 10Mi
