---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/backend-config: '{"default": ""{{ .Values.appName }}"-websocket-timeout-config"}'
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    env: "{{ .Values.environment }}"
  name: "{{ .Values.appName }}"
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: "{{ .Values.appName }}"
    env: "{{ .Values.environment }}"

---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  labels:
    env: "{{ .Values.environment }}"
  name: "{{ .Values.appName }}-websocket-timeout-config"
spec:
  timeoutSec: 1200

---
apiVersion: net.gke.io/v1
kind: ServiceExport
metadata:
  labels:
    env: "{{ .Values.environment }}"
  name: "{{ .Values.appName }}"
